In [1]:
# matrix = [[1.0, 2.0, 3.5, 3.0, 4.0], [2.5, 2.0, 1.5, 2.0, 1.0], [2.5, 2.0, 3.0, 1.0, 2.0], [4.0, 3.5, 3.5, 4.0, 1.0]]

In [23]:
with open('matrix.txt') as f:
    matrix = [list(map(float, row.split())) for row in f.readlines()]
matrix

[[1.0, 2.0, 3.5, 3.0, 4.0],
 [2.5, 2.0, 1.5, 2.0, 1.0],
 [2.5, 2.0, 3.0, 1.0, 2.0],
 [4.0, 3.5, 3.5, 4.0, 1.0]]

In [24]:
import numpy as np

matrix = np.array(matrix)
B = matrix@matrix.T
C = matrix.T@matrix

In [25]:
B

array([[42.25, 21.75, 28.  , 39.25],
       [21.75, 17.5 , 18.75, 31.25],
       [28.  , 18.75, 24.25, 33.5 ],
       [39.25, 31.25, 33.5 , 57.5 ]])

In [4]:
C

array([[29.5 , 26.  , 28.75, 26.5 , 15.5 ],
       [26.  , 24.25, 28.25, 26.  , 17.5 ],
       [28.75, 28.25, 35.75, 30.5 , 25.  ],
       [26.5 , 26.  , 30.5 , 30.  , 20.  ],
       [15.5 , 17.5 , 25.  , 20.  , 22.  ]])

In [19]:
row_prod_b = np.prod(B,axis=1)
row_prod_b

array([1009912.3125   ,  223022.4609375,  426496.875    , 2362666.015625 ])

In [27]:
# коэффициенты обобщенной оценки объектов
ga = np.power(row_prod_b, 1/len(B))
cga = ga / np.sum(ga)
cga

array([0.26821207, 0.18386309, 0.21621527, 0.33170956])

In [29]:
# коэффициенты компетентности экспертов
row_prod_с = np.prod(C,axis=1)
ec = np.power(row_prod_с, 1/len(C))
cec = ec / np.sum(ec)
cec

array([0.19829562, 0.193934  , 0.23710756, 0.21185808, 0.15880474])

In [30]:
with open('result.txt', 'w') as file:
    file.write("Коэффициенты обобщенной оценки объектов:\n")
    np.savetxt(file, cga, fmt='%.4f', newline=' ')

    file.write("\n\nКоэффициенты компетентности экспертов:\n")
    np.savetxt(file, cec, fmt='%.4f', newline=' ')