In [1]:
import numpy as np

П - покупательский спрос, А - стратегия сбыта. В матрице объем оборота. Состояния спроса представлены вероятносятями probs

In [3]:
matrix = [
    [33,10,20,26.5],
    [50,67,11.5,25],
    [23.5,35,40,58.5]
]

matrix = np.array(matrix)

probs = [0.3, 0.2, 0.4, 0.1]
probs = np.array(probs)
# alf = 0.5

# Байес

По критерию Байеса за оптимальные принимается та стратегия (чистая) Ai, при которой максимизируется средний выигрыш.

In [5]:
# умножим спрос на вероятность
matrix_n = matrix * probs[:, np.newaxis].T
matrix_n

array([[ 9.9 ,  2.  ,  8.  ,  2.65],
       [15.  , 13.4 ,  4.6 ,  2.5 ],
       [ 7.05,  7.  , 16.  ,  5.85]])

In [7]:
# Складываем спрос
[sum(x) for x in matrix_n]

[22.549999999999997, 35.5, 35.9]

In [11]:
# берем максимальный
max([sum(x) for x in matrix_n])

35.9

Лучшая стратегия 3

# Лаплас

Если вероятности состояний природы правдоподобны, для их оценки используют принцип недостаточного основания Лапласа, согласно которого все состояния природы полагаются равновероятными \\
q1 = q2 = ... = qn = 1/n.
qi = 1/4

In [14]:
probs_l = np.array([1/len(matrix[0])] * len(matrix[0]))
probs_l

array([0.25, 0.25, 0.25, 0.25])

In [15]:
matrix_n = matrix * probs_l[:, np.newaxis].T
matrix_n

array([[ 8.25 ,  2.5  ,  5.   ,  6.625],
       [12.5  , 16.75 ,  2.875,  6.25 ],
       [ 5.875,  8.75 , 10.   , 14.625]])

In [17]:
# Складываем спрос
[sum(x) for x in matrix_n]

[22.375, 38.375, 39.25]

In [16]:
# берем максимальный
max([sum(x) for x in matrix_n])

39.25

# Вальд

По критерию Вальда за оптимальную принимается чистая стратегия, которая в наихудших условиях гарантирует максимальный выигрыш, т.е.
a = max(min aij)
Критерий Вальда ориентирует статистику на самые неблагоприятные состояния природы, т.е. этот критерий выражает пессимистическую оценку ситуации.

In [18]:
[min(x) for x in matrix]

[10.0, 11.5, 23.5]

# Севидж

Критерий минимального риска Севиджа рекомендует выбирать в качестве оптимальной стратегии ту, при которой величина максимального риска минимизируется в наихудших условиях, т.е. обеспечивается:
a = min(max rij)
Критерий Сэвиджа ориентирует статистику на самые неблагоприятные состояния природы, т.е. этот критерий выражает пессимистическую оценку ситуации.
Находим матрицу рисков.
Риск – мера несоответствия между разными возможными результатами принятия определенных стратегий. Максимальный выигрыш в j-м столбце bj = max(aij) характеризует благоприятность состояния природы.
1. Рассчитываем 1-й столбец матрицы рисков.
r11 = 50 - 33 = 17; r21 = 50 - 50 = 0; r31 = 50 - 23.5 = 26.5;  и т.д

In [21]:
# максимумы в стобцах
max_values = matrix.max(axis=0)
max_values

array([50. , 67. , 40. , 58.5])

In [23]:
# из максимального выигрыша в каждом столбце вычитаем и значения столбца. и берем максимум для каждой строки. Берем минимальное значение, как лучшую стратегию
[max(x) for x in max_values - matrix]

[57.0, 33.5, 32.0]

# Гурвиц

Критерий Гурвица является критерием пессимизма - оптимизма. За (оптимальную принимается та стратегия, для которой выполняется соотношение:
max(si)
где si = y min(aij) + (1-y)max(aij)
При y = 1 получим критерий Вальде, при y = 0 получим – оптимистический критерий (максимакс).
Критерий Гурвица учитывает возможность как наихудшего, так и наилучшего для человека поведения природы. Как выбирается y? Чем хуже последствия ошибочных решений, тем больше желание застраховаться от ошибок, тем y ближе к 1.
Рассчитываем si.
s1 = 0.5•10+(1-0.5)•33 = 21.5 и т.д

In [26]:
matrix.tolist()

[[33.0, 10.0, 20.0, 26.5], [50.0, 67.0, 11.5, 25.0], [23.5, 35.0, 40.0, 58.5]]

In [29]:
y = 0.5
[y*min(x)+(1-y)*max(x) for x in matrix]

[21.5, 39.25, 41.0]